name: Rules-Remake
main: NurAzliYT\Rules\Main
api: 5.0.0
version: 1.0.0
authors: ["NurAzliYT, NurAzli, MauslaGames"]
description: "Rules Remake For Your Server"

commands:
rules:
permission: rulesui.command
description: "Open Server Rules"

permissions:
rulesui.command:
default: true
